<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="MsgTypeIdentifierWSWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/MsgTypeIdentifierWSWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/MsgTypeIdentifierWSWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://msgtypeid/">
    <import location="MsgTypeIdentifierWS.wsdl" namespace="http://msgtypeid/"/>
    <plnk:partnerLinkType name="MsgTypeIdentifierWSLinkType">
        <plnk:role name="MsgTypeIdentifierWSRole" portType="ns:MsgTypeIdentifierWS"/>
    </plnk:partnerLinkType>
</definitions>
