<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="soapCountriesWSDLWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/soapCountriesWSDLWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/soapCountriesWSDLWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://j2ee.netbeans.org/wsdl/DatabaseBC/src/soapCountriesWSDL">
    <import location="soapCountriesWSDL.wsdl" namespace="http://j2ee.netbeans.org/wsdl/DatabaseBC/src/soapCountriesWSDL"/>
    <plnk:partnerLinkType name="soapCountriesWSDLLinkType">
        <plnk:role name="soapCountriesWSDLRole" portType="ns:soapCountriesWSDLPortType"/>
    </plnk:partnerLinkType>
</definitions>
